  @Test
  public void test_non_compliant9() {
    //Test JUnit 4
    try {
      org.junit.Assert.assertArrayEquals(new String[1], new String[1]); // Noncompliant {{Don't use assertArrayEquals() inside a try-catch catching an AssertionError.}}
      org.junit.Assert.assertEquals(0,0); // Noncompliant {{Don't use assertEquals() inside a try-catch catching an AssertionError.}}
      org.junit.Assert.assertNotEquals(0, 0); // Noncompliant
      org.junit.Assert.assertNotSame(0 ,0); // Noncompliant
      org.junit.Assert.assertSame(0 ,0); // Noncompliant
      org.junit.Assert.assertNull(null); // Noncompliant
      org.junit.Assert.assertNotNull(null); // Noncompliant
      org.junit.Assert.assertFalse(false); // Noncompliant
      org.junit.Assert.assertTrue(false); // Noncompliant
      org.junit.Assert.assertThat(false, is(false)); // Noncompliant
      org.junit.Assert.fail("Expected an AssertionError!"); // Noncompliant
    } catch (AssertionError e) {}
  }

