  int throwException(int x) throws Exception {
    return x;
  }

