  public ExitWithException(int i) throws MyException {
    self = getOtherSelf(); // Compliant
  }

