  @Test
  void verify_should_fail_when_using_incorrect_secondaryLocation2() throws IOException {
    IssuableSubscriptionVisitor visitor = new FakeVisitor().withDefaultIssues();
    try {
      CheckVerifier.newVerifier()
        .onFile("src/test/files/JavaCheckVerifierIncorrectSecondaryLocation2.java")
        .withCheck(visitor)
        .verifyIssues();
      Fail.fail("Should have failed");
    } catch (AssertionError e) {
      assertThat(e).hasMessage("Secondary locations: expected: [5] unexpected: []. In JavaCheckVerifierIncorrectSecondaryLocation2.java:10");
    }
  }

