  private Object test_unknown_exception() throws ExA {
    try {
      return unknown_method(); // flow@unknown {{Exception is thrown.}}
    } catch (UnknownException ex) { // flow@unknown {{Exception is caught.}}
      return null;
    }
  }

